---
- hosts: aws
  # user: ubuntu
  # gather_facts: False
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
    - name: Delete content & directory
      file:
        state: absent
        path: ~/chatroom/
    - name: Clone Repository
      git:
        repo: https://github.com/plh2/chatroom.git
        dest: ~/chatroom
        clone: yes
        update: yes
        version: feat/terraform-aws

    - name: install dependences
      command:
        cmd: yarn run bootstrap
        chdir: ~/chatroom
    # - name: build
    #   command:
    #     chdir: ~/chatroom
    #     cmd: npm run build
    - name: deploy
      command:
        chdir: ~/chatroom
        cmd: npm run deploy
...
