const ACTION_TYPE = {
    CREATE_TASK: 'CREATE_TASK',
    DELETE_TASK: 'DELETE_TASK',
    MOVE_BACK_TASK: 'MOVE_BACK_TASK',
    MOVE_FORWARD_TASK: 'MOVE_FORWARD_TASK',
    SELECT_TASK: 'SELECT_TASK',
    SAVE_USER_INFO: 'SAVE_USER_INFO'
}


export {
    ACTION_TYPE
}